// import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "30 Days React tutorial layout",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	// header layout
	const header = (
		<header>
			<div>
				<Link href='/'>
					<h1>30 Days React tutorial</h1>
				</Link>
				<p>React tutorial description</p>
				<br />
			</div>
		</header>
	);

	// footer layout
	const footer = (
		<footer>
			<div>
				<br />
				<p>developed by kaZantip_xD</p>
			</div>
		</footer>
	);

	return (
		<html lang='en'>
			{header}
			{children}
			{footer}
		</html>
	);
}
