import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "30 Days React tutorial layout",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	// header layout
	const header = (
		<header className='text-center bg-slate-800 py-7 mb-5'>
			<div>
				<h1 className='text-3xl text-gray-50 font-bold mb-2'>
					<Link href='/'>30 Days React tutorial</Link>
				</h1>

				<p className='text-xl text-slate-300'>React tutorial description</p>
			</div>
		</header>
	);

	// footer layout
	const footer = (
		<footer className='text-right pr-10 bg-slate-800 py-7 mt-5'>
			<div>
				<p className='text-xl text-slate-100'>developed by kaZantip_xD</p>
			</div>
		</footer>
	);

	return (
		<html lang='en'>
			<head />
			<body className='transition-all '>
				{header}
				<div className='mx-auto md:max-w-4xl max-w-[90%]'>{children}</div>
				{footer}
			</body>
		</html>
	);
}
